namespace: laurobmb
name: aws
version: 1.0.1
readme: README.md
authors:
- Lauro Gomes <lagomes@redhat.com>
description: Modulo para criar contas na aws
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/laurobmb/ansible_statusinvest_collection
documentation: https://github.com/laurobmb/ansible_statusinvest_collection/docs/
homepage: https://github.com/laurobmb
issues: https://github.com/laurobmb/ansible_statusinvest_collection/issues
build_ignore:
- '*.pyc'
- galaxy.yml
- playbooks/sensitive
- '*.tar.gz'
- plugins/modules/module_statusinvest_acoes.py
- plugins/modules/module_statusinvest_fundos.py
