namespace: laurobmb
name: aws
version: 1.0.6
readme: README.md
authors:
- Lauro Gomes <lagomes@redhat.com>
description: Modulo para criar contas na aws
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/laurobmb/aws
documentation: https://github.com/laurobmb/aws/tree/main/docs
homepage: https://github.com/laurobmb
issues: https://github.com/laurobmb/aws/issues
build_ignore:
- '*.pyc'
- galaxy.yml
- playbooks/sensitive
- '*.tar.gz'
