namespace: laurobmb
name: aws
version: 1.0.7
readme: README.md
authors:
- Lauro Gomes <lagomes@redhat.com>
- Lauro Gomes <laurobmb@gmail.com>
description: This Ansible module automates the creation of new AWS accounts and the movement of existing accounts between Organizational Units (OUs). It operates declaratively and idempotently, waiting for processes to complete to ensure the accounts are in the desired state.
license:
- GPL-3.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/laurobmb/aws
documentation: https://github.com/laurobmb/aws/tree/main/docs
homepage: https://github.com/laurobmb
issues: https://github.com/laurobmb/aws/issues
build_ignore:
- '*.pyc'
- galaxy.yml
- playbooks/sensitive
- '*.tar.gz'
